### PR TITLE
Use git submodule for discount library

### PR DESCRIPTION
**Pull request by demonpig**
This commit is in response to the following [issue](https://github.com/Philip-Scott/Notes-up/issues/54).

**Testing**
I have tested this commit by cloning my forked repository and checking out my sub-module branch. Then it was a simple:
```
mkdir build ; cd build
cmake ..
make
```

I have configured CMake to update the module, checkout version, copy to build directory, and reset submodule to master. The reason for resetting to master is just so the user / developer will know that he or she is always on the most current version of discount.

### CODE REVIEW

**Comment by demonpig** [comment]
Discovered an issue with this request. Not exactly sure what is going on but I need to do more testing.

**Comment by demonpig** [comment]
Figured it out. Will post an update later this week or possibly this weekend.

**Comment by demonpig** [comment]
Sorry for being so late on this commit. But when you have time, please look over this commit.

**Comment by demonpig** [comment]
Just wondering if there was anything wrong with this pull request?

**Comment by Philip-Scott** [comment]
No, it seems correct. I'm worried a bit about how Launchpad and Houston (the elementary builder) will react to git modules when it imports, so i want to merge on a weekend where i have some time (And sadly, I've been super busy lately)

**Comment by khurshid-alam** [comment]
Launchpad can't handle sub-modules, so a big no from me. Actually it can handle sub-module, but it can't use http during compilation (same for debian)

**Comment by demonpig** [comment]
I am not familiar with using launchpad. So its not able to complete the `git checkout` of the submodule?

**Comment by Philip-Scott** [comment]
Thank you @khurshid-alam for your comment about Launchpad :)

**Comment by Philip-Scott** [comment]
Closing since the library was removed in favor of libmarkdown :)

**Pull request closed without merging**
