### PR TITLE
Add .gitignore file to project

### PR DESCRIPTION
**Pull request by demonpig**
I think this would benefit the project if it had a .gitignore file. It would help in isolating what files were changed by the developer. In addition, I think it will eliminate the chance of any auto-generated files being committed to the repository.

### CODE REVIEW

**Comment by Philip-Scott** [comment]
I do agree with having a .gitignore, but the file you added ignores CMake (Which is important) and the files from discount (Which could also change later). And the file also doesn't need to include all the windows things in it ;P

**Comment by demonpig** [comment]
This is the output of the of a clean build that I get without the .gitignore file. All of these files (excluding the build directory) are generated via the configure/build command in CMakeLists.txt. So with the .gitignore, I am simply trying to block compiled objects and generated scripts from possibly being added to the commit.

    maxmitschke@desktop1:~/Development/test/Notes-up> git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    Changes not staged for commit:
        (use "git add <file>..." to update what will be committed)
        (use "git checkout -- <file>..." to discard changes in working directory)
    
	    modified:   src/config.vala
    
    Untracked files:
    (use "git add <file>..." to include in what will be committed)

	  build/
	  deps/discount/Csio.o
	  deps/discount/Makefile
	  deps/discount/basename.o
	  deps/discount/blocktags
	  deps/discount/config.cmd
	  deps/discount/config.h
	  deps/discount/config.log
	  deps/discount/config.mak
	  deps/discount/config.md
	  deps/discount/config.sub
	  deps/discount/css.o
	  deps/discount/docheader.o
	  deps/discount/dumptree.o
	  deps/discount/emmatch.o
	  deps/discount/flags.o
	  deps/discount/generate.o
	  deps/discount/github_flavoured.o
	  deps/discount/html5.o
	  deps/discount/libmarkdown
	  deps/discount/libmarkdown.a
	  deps/discount/librarian.sh
	  deps/discount/main.o
	  deps/discount/markdown
	  deps/discount/markdown.o
	  deps/discount/mkdio.h
	  deps/discount/mkdio.o
	  deps/discount/mktags
	  deps/discount/pgm_options.o
	  deps/discount/resource.o
	  deps/discount/setup.o
	  deps/discount/src/
	  deps/discount/tags.o
	  deps/discount/tmp/
	  deps/discount/toc.o
	  deps/discount/version.c
	  deps/discount/version.o
	  deps/discount/xml.o
	  deps/discount/xmlpage.o
    
    no changes added to commit (use "git add" and/or "git commit -a")

**Comment by demonpig** [comment]
I can take out all the windows extensions if you would like. They were added via the gitignore service.

**Comment by demonpig** [comment]
I think the items related to cmake are for files that are generated via `cmake` command. I am going to test to make sure that any important CMakeFiles files, that are already present in the repo, are not being excluded.

**Comment by Philip-Scott** [comment]
Well, the gitignore file could just contain this, couldn't it :wink: 

```
build/
  deps/discount/Csio.o
  deps/discount/Makefile
  deps/discount/basename.o
  deps/discount/blocktags
  deps/discount/config.cmd
  deps/discount/config.h
  deps/discount/config.log
  deps/discount/config.mak
  deps/discount/config.md
  deps/discount/config.sub
  deps/discount/css.o
  deps/discount/docheader.o
  deps/discount/dumptree.o
  deps/discount/emmatch.o
  deps/discount/flags.o
  deps/discount/generate.o
  deps/discount/github_flavoured.o
  deps/discount/html5.o
  deps/discount/libmarkdown
  deps/discount/libmarkdown.a
  deps/discount/librarian.sh
  deps/discount/main.o
  deps/discount/markdown
  deps/discount/markdown.o
  deps/discount/mkdio.h
  deps/discount/mkdio.o
  deps/discount/mktags
  deps/discount/pgm_options.o
  deps/discount/resource.o
  deps/discount/setup.o
  deps/discount/src/
  deps/discount/tags.o
  deps/discount/tmp/
  deps/discount/toc.o
  deps/discount/version.c
  deps/discount/version.o
  deps/discount/xml.o
  deps/discount/xmlpage.o
```

**Comment by Philip-Scott** [comment]
Oh and sorry, I saw deps/discount/src and assumed that's where the discount files were, didn't realize those weren't added before :sweat_smile: 

But yeah, the CMake files are important. If you could remove those and the windows files i can merge it :)

**Comment by demonpig** [comment]
I do not really use windows that much. would that be just DLL and EXE file extensions?

**Comment by Philip-Scott** [comment]
I think you can remove everything above line 68, and just add the files git tells you it's untracked :)

**Comment by demonpig** [comment]
OK. I have just pushed a new commit with the suggested changes.

**Comment by Philip-Scott** [comment]
Perfect! Thank you :)

**Pull request merged**
