### PR TITLE
Added an openSUSE software link

### PR DESCRIPTION
**Pull request by Mailaender**
We packaged it outside of the Ubuntu/elementaryOS sphere as well.

### CODE REVIEW

**Comment by Philip-Scott** [comment]
Can i just ask something? Who is `we` and who will be keeping it updated for openSUSE? :)

**Comment by Mailaender** [comment]
https://en.opensuse.org/Portal:Pantheon lists everything. It is essentially a very small team. I just filed an update: https://build.opensuse.org/request/show/512134

**Comment by Philip-Scott** [comment]
Alright :) And is it working already?

**Comment by demonpig** [comment]
@Mailaender when building Notes-Up be sure to pass `-Dnoele=1` into the cmake commands. This will disable the contractor functionality of Notes-Up. If you want it this way, then maybe include Contractor in the Requires of the SPEC file.

The image below was run on my installation of Tumbleweed.
screenshot from 2017-07-23 23-33-20

**Comment by Mailaender** [comment]
That is good to know. I had contractor installed so I didn't notice the dependency RPM won't pick up by itself. Fixed https://build.opensuse.org/request/show/512368

**Pull request merged**
